### ISSUE TITLE
Pandora on ATV2 loads, and logs in, can see stations, but never plays music?!

### ISSUE THREAD

**Issue by chringram** [rivy/xbmc-script.audio.pandora#5] opened 2014-01-16 03:15 UTC
Pandora on ATV2 loads, and logs in, can see stations, but never plays music?!

**Comment by rivy** [comment] 2014-01-16 05:21
Can you provide some more information? ... versions of the plugin / XBMC? XBMC log?

Did you ever have a previous working version?

Thanks.

**Comment by chringram** [comment] 2014-01-16 18:47
Thanks Roy!
It’s the first time using the plug in (no previous versions installed). Tried restarting the apple tv, then deleting the plug in and re-installing, but still same issue. Take note that when I choose a Pandora ‘channel’ I hear a ‘swish’ sound as if another menu is to come up… but the screen does not change. I tried selecting the PLAY icon, and I hear a ‘swish’ sound, but still no music.

Pandora Plug In v1.2.11 (downloaded zip from XBMC directly from ATV2)
XBMC v12.3
XBMC log … saved it but would need a link to a tutorial on how to copy it over (can I do it with an SSH connection?)

**Comment by rivy** [comment] 2014-01-18 05:10
I don't have any experience using the ATV, so I'm not actually sure how to copy the XBMC. 

But. if you have SSH access, you should be able to copy the file with SCP (see http://www.howtogeek.com/66776/how-to-remotely-copy-files-over-ssh-without-entering-your-password ).

It looks like the log file should be in <code>/private/var/mobile/Library/Preferences/xbmc.log</code>.

The thread @ http://forum.xbmc.org/showthread.php?tid=94906 seems to have a lot of info on how to access the log (including how to setup/access a debug log, and a plugin to simplify access).

**Comment by chringram** [comment] 2014-01-22 00:53
Problem resolved - all music plays as expected. The solution was to go into the ADD ON "configuration" area and make sure the quality of audio is set to MP3.

**Comment by rivy** [comment] 2014-01-22 01:04
There is a problem with the internal xbmc.Player() that requires a specific call parameter that has recently been deprecated. When I removed the deprecated parameter, the internal player stopped recognizing MP4 audio streams (Medium or Low quality from Pandora), although MP3 streams (High quality) still worked fine.

I replaced the previous call parameter, and the problem is fixed one of  the later revisions. If you get the latest master (R-v2.3.1), it should work for all quality levels.

URLref: http://forum.xbmc.org/showthread.php?tid=173887&pid=1603435#pid1603435

**Closed as completed by rivy** 2014-01-22 01:04 UTC
Labels: bug, fixed
